### ISSUE TITLE
Add javascript code samples

### ISSUE THREAD

**Issue by lmatuszek** [awsdocs/amazon-transcoder-developer-guide#3]
The sample-code.md file doesn't include any Javascript examples.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
