### ISSUE TITLE
Expand PHP code samples

### ISSUE THREAD

**Issue by lmatuszek** [awsdocs/amazon-transcoder-developer-guide#4]
The PHP code samples don't include thumbnail sections.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
