### ISSUE TITLE
Add Node.js sample code

### ISSUE THREAD

**Issue by lmatuszek** [awsdocs/amazon-transcoder-developer-guide#5]
Add sample code for Node.js.

**Comment by NazimFilzer** [comment]
Could u elaborate

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
